[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "yarn"]

[build.nixpacksPlan.phases.install]
cmds=["yarn install"]

[build.nixpacksPlan.phases.build]
cmds=["yarn run build"]

[build.nixpacksPlan.phases.start]
cmds=["yarn run start"]